# Generated by Django 5.1.3 on 2024-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_user_teacher_teacher_student_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='students',
            field=models.ManyToManyField(related_name='students', to='myapp.student'),
        ),
    ]
